# Generated by Django 4.2.1 on 2023-06-08 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_is_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='city',
        ),
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'unique_together': {('product', 'inventory')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.ManyToManyField(through='shop.InventoryProduct', to='shop.inventory'),
        ),
    ]
