# Generated by Django 4.2.1 on 2023-06-08 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_city_inventoryproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.city'),
        ),
    ]
