# Generated by Django 4.2.1 on 2023-06-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='province_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Type',
            field=models.CharField(choices=[('classy', 'درجه یک'), ('medium', 'درجه دو'), ('lowAvrage', 'درجه سه')], max_length=20),
        ),
    ]
